### ISSUE TITLE
代码不规范-使用代码覆盖方法无法覆盖全部分支

### ISSUE THREAD

**Issue by turling-hunter** [jfree/jfreechart#123]
JFreeChart-1.0.13     
  org.jfree.data
    Range.java
public double constrain(double value) {
        double result = value;
        if (!contains(value)) {
            if (value > this.upper) {
                result = this.upper;
            }
            else if (value < this.lower) {
                result = this.lower;
            }
        }
        return result;
    }

代码不规范，使用单元测试时，代码覆盖无法覆盖else if 的所有分支
建议代码：
public double constrain(double value) {
        double result = value;
        if (!contains(value)) {
            if (value > this.upper) {
                result = this.upper;
            }
            result = this.lower;
        }
        return result;
    }

**Comment by kimim** [comment]
this issue says that the coverage of unit test is not completed. bellow is the suggested one. But the suggested one seems in the same logic?

**Comment by jfree** [comment]
Yes, the logic is the same but the reporter is pointing out that the check "if (value < lowerbound)" is redundant, which it is.  I'll replace the method with:

    public double constrain(double value) {
        if (contains(value)) {
            return value;
        }
        if (value > this.upper) {
            return this.upper;
        } 
        return this.lower;
    }

**Comment by jfree** [comment]
In fact, one test (the value Double.NaN) fails for this, so the required method is:

    public double constrain(double value) {
        if (contains(value)) {
            return value;
        }
        if (value > this.upper) {
            return this.upper;
        }
        if (value < this.lower) {
            return this.lower;
        }
        return value; // covers Double.NaN
    }
