### ISSUE TITLE
Pie Chart always calculated to 100 %

### ISSUE THREAD

**Issue by irudayambics** [jfree/jfreechart#125]
Output:
Single – 26.563%             - Reflected as 27% in pie chart
Married – 69.531%          - Reflected as 70% in pie chart
Divorced – 3.906%           - Reflected as 3% in pie chart

I am using v1.5.0 of JFree chart. Please advise.

**Comment by thackel** [comment]
What do you expect?
If you don't want to see the rounded values just use your own `PieSectionLabelGenerator`.

**Comment by irudayambics** [comment]
Thanks for your reply! Can you share some code snippet? 

I expect the values as it is. I only pass 26, 69 and 3 to Pie Chart. Because my requirement is to discard all the decimal points and pass the whole number to Pie Chart.
Example:
Single -26 => Expecting 27 in Pie Chart
Married - 69 => Expecting 69 in Pie Chart
Divorced - 3 => Expecting 3 in Pie Chart.

My own PieSectionLabelGenenator is below.  getTruncateDecimalFormatInstanceByFormat() is my custom function to return DecimalFormat to truncate the values without rounding.

PieSectionLabelGenerator generator = new StandardPieSectionLabelGenerator("{2}", getTruncateDecimalFormatInstanceByFormat("0"), "0%"));

ColorConfigurator.setLabelGenerator(generator);

ColorConfigurator.setLegendLabelGenerator(new StandardPieSectionLabelGenerator("{0}", getTruncateDecimalFormatInstanceByFormat("0"), "0%"));



private DecimalFormat getTruncateDecimalFormatInstanceByFormat(String format) {
		if(format == null) {
			logger.debug("getTruncateDecimalFormatInstanceByFormat=> format is null. So returning defaul DecimalFormat");
			return new DecimalFormat();
		} else {
			DecimalFormat decimalFormat = new DecimalFormat(format);
			decimalFormat.setRoundingMode(RoundingMode.DOWN);
			return decimalFormat;	
		}		
	}

**Comment by thackel** [comment]
Now just set your custom label generator in the pie plot (`PiePlot.setLabelGenerator()`)

**Comment by irudayambics** [comment]
It's already set. Please see my code snippet above. 

ColorConfigurator.setLabelGenerator(generator);

**Comment by thackel** [comment]
It's really easy. Just read the API doc...

Default:
![Default](https://user-images.githubusercontent.com/1008148/59922338-e2726680-9430-11e9-91b1-0d4310076a76.png)

Just Percent output:
`StandardPieSectionLabelGenerator("{2}"`

![Default-Just-Percent](https://user-images.githubusercontent.com/1008148/59922415-046be900-9431-11e9-99f2-c812d7af6777.png)

Default all formats:
`StandardPieSectionLabelGenerator("{0} = {1} ({2})")`

![Default-Just-All-Formats](https://user-images.githubusercontent.com/1008148/59922916-42b5d800-9432-11e9-825b-ee544427a066.png)

Totally Custom:
`StandardPieSectionLabelGenerator("{2} is {1} of {0}",
				NumberFormat.getNumberInstance(Locale.UK), NumberFormat.getPercentInstance(Locale.UK))`

![Totally-Custom](https://user-images.githubusercontent.com/1008148/59922981-6f69ef80-9432-11e9-8b92-af8b279aeeac.png)

Just modify the PercentInstance when you need more/less digits...

**Comment by jfree** [comment]
Good answer, closing.
