### ISSUE TITLE
Developers Guide - Premium Forum & Support

### ISSUE THREAD

**Issue by C4J** [jfree/jfreechart#127]
Just got the Developers Guide and downloaded the source to the demo's which was useful. Apparently there is also access to the Premium Forum - however even though I've registered its not possible to post and it looks rather unused now ? Whats the situation?

**Comment by jfree** [comment]
Years ago there was a possibility to pay for premium support of JFreeChart.  There was some demand for that, but not enough to make it a success so it was discontinued.   However, there was useful info in the forum, so it is still up in read only mode.  You can't post questions there anymore.
