### ISSUE TITLE
Versions question

### ISSUE THREAD

**Issue by C4J** [jfree/jfreechart#128]
Can I replace jfreechart jar file version 1.0.19 with 1.15 without breaking anything. The older version is included with JasperReports which I do use (but without graphs) - I would now like to include graphs in my application but I don't know if I can update to the latest version without breaking anything or need to change dependencies which might also been needed by JasperReports.

**Comment by jfree** [comment]
No, there are breaking API changes.  These are summarised in the README file, and also issue 66:

https://github.com/jfree/jfreechart/issues/66
