### ISSUE TITLE
Fill Legend Color box

### ISSUE THREAD

**Issue by goranschwarz** [jfree/jfreechart#131]
This is more a question than a "issue"

But I have spend many hours to "fill" the color box of a Legend Item

Take the followning example:
https://www.boraji.com/jfreechart-time-series-chart-example

In he above example, I want to (at the bottom, the Legend):
- The red line "Series1" should be a filled box with the same color as in the chart
- The blue line "Series2" should be a filled box with the same color as in the chart

I do **not** want to set the lines in the chart to be thicker... because I have **many** lines in the chart... I just want to change the size (or fill) of the color box in the legends

So from:
![image](https://user-images.githubusercontent.com/4483245/65391575-0f555300-dd6b-11e9-9ed6-0f4ae3282381.png)

to:
![image](https://user-images.githubusercontent.com/4483245/65391594-3f9cf180-dd6b-11e9-88c1-25a5df8180bd.png)

**Comment by thackel** [comment]
I would overwrite the ```getLegendItem()``` method of the renderer. There you can define the shape of the legend item, which is normally the same as the rendered line.

**Comment by goranschwarz** [comment]
Thanks, I found a solution in: 
http://www.jfree.org/forum/viewtopic.php?f=3&t=29031&p=168280&hilit=getLegendItem+XYLineAndShapeRenderer#p168280

Here are the result:
![image](https://user-images.githubusercontent.com/4483245/65494460-30c25600-deb5-11e9-85c7-b410fc2fb263.png)

and the code:
```
private JFreeChart createChart(XYDataset dataset, String graphTitle, String timeAxisLabel, String valueAxisLabel, int maxValue) 
{
	JFreeChart chart = ChartFactory.createTimeSeriesChart(graphTitle, timeAxisLabel, valueAxisLabel, dataset, true, true, false);
	XYPlot plot = (XYPlot) chart.getPlot();

	// Set thicker lines
	boolean thickLines = false;
	if (thickLines)
	{
		int seriesCount = plot.getSeriesCount();
		for (int i = 0; i < seriesCount; i++)
			plot.getRenderer().setSeriesStroke(i, new BasicStroke(2));
	}

	// Special Renderer that creates a LegenItem that is square and FILLED
	XYItemRenderer renderer = new XYLineAndShapeRenderer(true, false) 
	{
		private static final long serialVersionUID = 1L;

		@Override
		public LegendItem getLegendItem(int datasetIndex, int series) 
		{
			if (getPlot() == null) 
				return null;

			XYDataset dataset = getPlot().getDataset(datasetIndex);
			if (dataset == null) 
				return null;

			String label = dataset.getSeriesKey(series).toString();
			LegendItem legendItem = new LegendItem(label, lookupSeriesPaint(series));
			legendItem.setLine(Plot.DEFAULT_LEGEND_ITEM_BOX);
			
			return legendItem;
		}
	};
	plot.setRenderer(renderer);

	// Set format of the time labels
	DateAxis axis = (DateAxis) plot.getDomainAxis();
	axis.setDateFormatOverride(new SimpleDateFormat("HH:mm"));
	
	// for Percent Graph: set MAX to 100%
	if (maxValue > 0)
	{
		NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
		rangeAxis.setRange(0.0, maxValue);
	}

	return chart;
}
```
