### ISSUE TITLE
JFreeChart has memory leaks

### ISSUE THREAD

**Issue by pjyoung** [jfree/jfreechart#132]
I have an app that creates a bunch of XY series plots - 65 in total for a number of instrument sensors. These plots are extended over time as new data points arrive but are limited to 10000 points for each series, so once each series is full - there should be of order 65*10000 XYDataItems in total. I have noticed that there are various JFreeChart data structures that continue to grow beyond this limit for each series. This is illustrated by the following VisualVM and JProfiler plots.

Note that the the objects Ellipse2D$Double and XYItemEntity have over 2.5M instances while the number of XYDataItem instances are only 381K - in line with the the expected number (ie in the example, not all of the 65 series have yet reached 10000 points).

So the question is - why are there 2.5M Ellipse2D$Double and XYItemEntity instances? And therefore, why do these plots take up so much memory? This behaviour is making the use of JFreeChart for this app impossible. The app is intended to run for periods of 24 hours with plots of telemetry data that are designed to highlight anomalies over the run period. JFreeChart features such as zooming and panning can then be used to zero in on when issues/trends occurred.

Advice on JFreeChart memory usage appreciated.

<img width="894" alt="image" src="https://user-images.githubusercontent.com/8550941/66884161-054a0b80-f01c-11e9-99e7-ec7d32eda6e2.png">

<img width="940" alt="image" src="https://user-images.githubusercontent.com/8550941/66884191-2874bb00-f01c-11e9-8108-d7e6d902a543.png">

**Comment by thackel** [comment]
As always:
Just provide a sample project which shows the increasing memory usage.

**Comment by pjyoung** [comment]
Ok - will work on putting together an example...

**Comment by pjyoung** [comment]
OK - I have a workaround... 

I have extended XYPlot with my own version that strips out some not needed code to do with shapes and other graphics, also removed the use of the EntityCollection which is where I think the leak is (ie entries are not removed as plot points are removed).

After > 5h of running I now see a very stable heap. I will run longer to be sure - but this compares very positively to the earlier heap plot. The second screenshot shows the heap difference from the start - note that only the expected number of XYDataItems has grown (from the JFree classes).

I won't work on a sample project - I am pressed for time - unless otherwise persuaded...

Here is my new code:

`
private static ChartTheme currentTheme = new StandardChartTheme("JFree");

  private JFreeChart createXYLineChart(String title, String xAxisLabel, String yAxisLabel, XYDataset dataset,
          PlotOrientation orientation) {

    NumberAxis xAxis = new NumberAxis(xAxisLabel);
    xAxis.setAutoRangeIncludesZero(false);
    NumberAxis yAxis = new NumberAxis(yAxisLabel);
    XYItemRenderer renderer = new CustomStandardXYItemRenderer();
    CustomXYPlot plot = new CustomXYPlot(dataset, xAxis, yAxis, renderer);
    plot.setOrientation(orientation);

    JFreeChart chart = new JFreeChart(title, JFreeChart.DEFAULT_TITLE_FONT, plot, false);
    currentTheme.apply(chart);
    return chart;

  }

  /**
   * PJY Extends the standard XYPlot to make simpler to tackle apparent memory leaks in default JFree class
   */
  private class CustomXYPlot extends XYPlot {

    public CustomXYPlot(XYDataset dataset, ValueAxis domainAxis, ValueAxis rangeAxis,
            XYItemRenderer renderer) {
      super(dataset, domainAxis, rangeAxis, renderer);
    }

    /**
     * Draws the plot within the specified area on a graphics device.
     * PJY - simpler version of draw - just do line plots - no shape rendering
     *
     * @param g2 the graphics device.
     * @param area the plot area (in Java2D space).
     * @param anchor an anchor point in Java2D space ({@code null} permitted).
     * @param parentState the state from the parent plot, if there is one ({@code null} permitted).
     * @param info collects chart drawing information ({@code null} permitted).
     */
    @Override
    public void draw(Graphics2D g2, Rectangle2D area, Point2D anchor, PlotState parentState, PlotRenderingInfo info) {

      // if the plot area is too small, just return...
      boolean b1 = (area.getWidth() <= MINIMUM_WIDTH_TO_DRAW);
      boolean b2 = (area.getHeight() <= MINIMUM_HEIGHT_TO_DRAW);
      if (b1 || b2) {
        return;
      }

      // record the plot area...
      if (info != null) {
        info.setPlotArea(area);
      }

      // adjust the drawing area for the plot insets (if any)...
      RectangleInsets insets = getInsets();
      insets.trim(area);

      AxisSpace space = calculateAxisSpace(g2, area);
      Rectangle2D dataArea = space.shrink(area, null);
      getAxisOffset().trim(dataArea);

      dataArea = integerise(dataArea);
      if (dataArea.isEmpty()) {
        return;
      }
      createAndAddEntity((Rectangle2D) dataArea.clone(), info, null, null);
      if (info != null) {
        info.setDataArea(dataArea);
      }

      // draw the plot background and axes...
      drawBackground(g2, dataArea);
      Map axisStateMap = drawAxes(g2, area, dataArea, info);

      PlotOrientation orient = getOrientation();

      Shape originalClip = g2.getClip();
      Composite originalComposite = g2.getComposite();

      g2.clip(dataArea);
      g2.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, getForegroundAlpha()));

      AxisState domainAxisState = (AxisState) axisStateMap.get(getDomainAxis());
      if (domainAxisState == null) {
        if (parentState != null) {
          domainAxisState = (AxisState) parentState.getSharedAxisStates().get(getDomainAxis());
        }
      }

      AxisState rangeAxisState = (AxisState) axisStateMap.get(getRangeAxis());
      if (rangeAxisState == null) {
        if (parentState != null) {
          rangeAxisState = (AxisState) parentState.getSharedAxisStates().get(getRangeAxis());
        }
      }
      if (domainAxisState != null) {
        drawDomainTickBands(g2, dataArea, domainAxisState.getTicks());
      }
      if (rangeAxisState != null) {
        drawRangeTickBands(g2, dataArea, rangeAxisState.getTicks());
      }
      if (domainAxisState != null) {
        drawDomainGridlines(g2, dataArea, domainAxisState.getTicks());
        drawZeroDomainBaseline(g2, dataArea);
      }
      if (rangeAxisState != null) {
        drawRangeGridlines(g2, dataArea, rangeAxisState.getTicks());
        drawZeroRangeBaseline(g2, dataArea);
      }

      // now draw annotations and render data items...
      boolean foundData = false;
      DatasetRenderingOrder order = getDatasetRenderingOrder();
      List<Integer> datasetIndices = getDatasetIndices(order);

      // render data items...
      for (int datasetIndex : datasetIndices) {
        XYDataset dataset = this.getDataset(datasetIndex);
        foundData = render(g2, dataArea, datasetIndex, info, null) || foundData;
      }

      if (!foundData) {
        drawNoDataMessage(g2, dataArea);
      }

      g2.setClip(originalClip);
      g2.setComposite(originalComposite);

      drawOutline(g2, dataArea);

    }

    /**
     * Returns the indices of the non-null datasets in the specified order.
     * PJY - copy of parent class as is private...
     *
     * @param order the order ({@code null} not permitted).
     *
     * @return The list of indices.
     */
    private List<Integer> getDatasetIndices(DatasetRenderingOrder order) {
      List<Integer> result = new ArrayList<Integer>();
      for (int i = 0; i < getDatasetCount(); i++) {
        XYDataset ds = getDataset(i);
        if (ds != null) {
          result.add(indexOf(ds));
        }
      }
      Collections.sort(result);
      if (order == DatasetRenderingOrder.REVERSE) {
        Collections.reverse(result);
      }
      return result;
    }

    /**
     * Trims a rectangle to integer coordinates.
     * PJY - copy of parent class as is private...
     *
     * @param rect the incoming rectangle.
     *
     * @return A rectangle with integer coordinates.
     */
    private Rectangle integerise(Rectangle2D rect) {
      int x0 = (int) Math.ceil(rect.getMinX());
      int y0 = (int) Math.ceil(rect.getMinY());
      int x1 = (int) Math.floor(rect.getMaxX());
      int y1 = (int) Math.floor(rect.getMaxY());
      return new Rectangle(x0, y0, (x1 - x0), (y1 - y0));
    }

  }

  private class CustomStandardXYItemRenderer extends StandardXYItemRenderer {

    public CustomStandardXYItemRenderer() {
      super();
    }

    /**
     * Draws the visual representation of a single data item.
     * PJY - Simplified version without any shapes etc. Done to cure memory leak issues.
     *
     * @param g2 the graphics device.
     * @param state the renderer state.
     * @param dataArea the area within which the data is being drawn.
     * @param info collects information about the drawing.
     * @param plot the plot (can be used to obtain standard color information etc).
     * @param domainAxis the domain axis.
     * @param rangeAxis the range axis.
     * @param dataset the dataset.
     * @param series the series index (zero-based).
     * @param item the item index (zero-based).
     * @param crosshairState crosshair information for the plot ({@code null} permitted).
     * @param pass the pass index.
     */
    @Override
    public void drawItem(Graphics2D g2, XYItemRendererState state,
            Rectangle2D dataArea, PlotRenderingInfo info, XYPlot plot,
            ValueAxis domainAxis, ValueAxis rangeAxis, XYDataset dataset,
            int series, int item, CrosshairState crosshairState, int pass) {

      boolean itemVisible = getItemVisible(series, item);

      PlotOrientation orientation = plot.getOrientation();
      Paint paint = getItemPaint(series, item);
      Stroke seriesStroke = getItemStroke(series, item);
      g2.setPaint(paint);
      g2.setStroke(seriesStroke);

      // get the data point...
      double x1 = dataset.getXValue(series, item);
      double y1 = dataset.getYValue(series, item);
      if (Double.isNaN(x1) || Double.isNaN(y1)) {
        itemVisible = false;
      }

      RectangleEdge xAxisLocation = plot.getDomainAxisEdge();
      RectangleEdge yAxisLocation = plot.getRangeAxisEdge();
      double transX1 = domainAxis.valueToJava2D(x1, dataArea, xAxisLocation);
      double transY1 = rangeAxis.valueToJava2D(y1, dataArea, yAxisLocation);

      if (getPlotLines()) {
        State s = (State) state;
        if (s.getSeriesIndex() != series) {
          // we are starting a new series path
          s.seriesPath.reset();
          s.setLastPointGood(false);
          s.setSeriesIndex(series);
        }

        // update path to reflect latest point
        if (itemVisible && !Double.isNaN(transX1)
                && !Double.isNaN(transY1)) {
          float x = (float) transX1;
          float y = (float) transY1;
          if (orientation == PlotOrientation.HORIZONTAL) {
            x = (float) transY1;
            y = (float) transX1;
          }
          if (s.isLastPointGood()) {
            // TODO: check threshold
            s.seriesPath.lineTo(x, y);
          } else {
            s.seriesPath.moveTo(x, y);
          }
          s.setLastPointGood(true);
        } else {
          s.setLastPointGood(false);
        }
        if (item == dataset.getItemCount(series) - 1) {
          if (s.getSeriesIndex() == series) {
            // draw path
            g2.setStroke(lookupSeriesStroke(series));
            g2.setPaint(lookupSeriesPaint(series));
            g2.draw(s.seriesPath);
          }
        }

      }
   }

  }
`


<img width="1345" alt="image" src="https://user-images.githubusercontent.com/8550941/66983372-24bc6380-f104-11e9-94b0-050bd596b327.png">

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/8550941/66983495-6947ff00-f104-11e9-8742-ef4dfe82573b.png">

**Comment by jfree** [comment]
The entity objects are created for each rendering of the chart, and returned to the caller.  They are not retained by JFreeChart (except one instance of the EntityCollection each time a ChartPanel is rendered).  They can use a lot of memory, but I have not seen a case where there is a memory leak in JFreeChart.  Without a test case to reproduce, I'll close this bug.
