### ISSUE TITLE
DatasetUtils.iterateZBounds() ignores parameter `includeInterval`

### ISSUE THREAD

**Issue by matinh** [jfree/jfreechart#141]
The class `DatasetUtils` has a method `iterateZBounds()` with a parameter `includeInterval` which is silently ignored inside the method:
https://github.com/jfree/jfreechart/blob/e9686b8b93476437cc8c5892189ca9df17e6f9d9/src/main/java/org/jfree/data/general/DatasetUtils.java#L1319-L1342

The method should check like other methods do,

    if (includeInterval && dataset instanceof IntervalXYZDataset) {

perform necessary casts and use `getStartZValue()`/`getEndZValue()` instead of `getZValue()` if appropriate.

**Comment by jfree** [comment]
I committed a test and a fix for this issue.
