### ISSUE TITLE
Prepared Graph Rendering Differs between Windows & Mac

### ISSUE THREAD

**Issue by StevenW-CA** [jfree/jfreechart#143]
It appears to be consistent behavior that a chart prepared on Windows will differ (albeit slightly) when compared (digitally) to the exact same chart prepared on Mac - even when "no data" is applicable and yet there are still diffs between the frame drawn on one platform vs. the other.

This hinders testing of the prepared images cross platform

Example: 

Chart prepared on Mac:

![example-mac](https://user-images.githubusercontent.com/61756015/75809942-745f9c80-5d3e-11ea-9abd-c138f365d083.png)

Chart prepared on Windows:

![example-win](https://user-images.githubusercontent.com/61756015/75809975-86d9d600-5d3e-11ea-8b31-d7c8574b42f3.png)

Diffs:

![example-mac-win-diffs](https://user-images.githubusercontent.com/61756015/75810001-922d0180-5d3e-11ea-818f-77229151d3ea.png)

**Comment by jfree** [comment]
This is just the nature of the Java graphics implementation, it is delegating drawing operations to native libraries on the underlying platforms and there will always be variations in the algorithms used for path drawing, anti-aliasing etc.
