### ISSUE TITLE
TimePeriodFormatException for illegal months.

### ISSUE THREAD

**Issue by tohidemyname** [jfree/jfreechart#146]
When I input an illegal year, I got a TimePeriodFormatException, but when I input an illegal month, I got an IllegalArgumentException. I notice that their source files throw different exceptions:

`  public static Year parseYear(String s) {
        // parse the string...
        int y;
       
       try {
      
             y = Integer.parseInt(s.trim());
       
       }
        catch (NumberFormatException e) {
       
           throw new TimePeriodFormatException("Cannot parse string.");
      
       }
    }
` 

`   public Month(int month, int year) {
  
      if ((month < 1) || (month > 12)) {
  
          throw new IllegalArgumentException("Month outside valid range.");
  
      }
  
  }
` 
I feel that TimePeriodFormatException is more informative. Can the exception of Month be modified?

**Comment by jfree** [comment]
The TimePeriodFormatException is used when converting a String (so the input has to conform to some kind of format).  In the case of the Month constructor, the parameter is an int so there isn't a formatting concern...just a valid range.
