### ISSUE TITLE
Using jfreechart with javafx

### ISSUE THREAD

**Issue by darthninja1** [jfree/jfreechart#15]
Hello,

I would like to use jfreechart with javafx (java 8). Is there an official release I should use?

Do I also need jcommon and fxgraphics2d?

Thanks,
DN

**Comment by jfree** [comment]
The latest release (1.0.19) includes JavaFX support.  JCommon is a dependency still, FXGraphics2D was incorporated directly in source form.  You need to rebuild JFreeChart from sources using the build-fx.xml file and make sure you are compiling on JDK 1.8.
