### ISSUE TITLE
Broken download link on website http://www.jfree.org/jfreechart/

### ISSUE THREAD

**Issue by zsewa** [jfree/jfreechart#158]
Hi, the download link in the navbar of http://www.jfree.org/jfreechart/ seems to be broken and gives the following error.

```
501 HTTPS Required. 
Use https://repo1.maven.org/maven2/
More information at https://links.sonatype.com/central/501-https-required
```

You may consider changing the link scheme from `http` to `https`. 

`https://repo1.maven.org/maven2/org/jfree/jfreechart/` instead of `http://repo1.maven.org/maven2/org/jfree/jfreechart/` is working just fine.

Thanks!

**Comment by jfree** [comment]
Thanks for the report, I fixed that just now.
