### ISSUE TITLE
Domain duplicate values

### ISSUE THREAD

**Issue by pepobit** [jfree/jfreechart#166]
When I create a scatter plot on the xomain axis I only have 2 values (0 and 1). 
Duplicates appear n times. How can I avoid duplicates appearing only once? 
Thanks

<img width="1081" alt="Captura de pantalla 2020-06-29 a las 0 15 35" src="https://user-images.githubusercontent.com/1220778/85959626-c7b8c300-b99d-11ea-8eea-df6a2fcdae76.png">

**Comment by jfree** [comment]
I'm guessing your axis is generating fractional tick values and you've overridden the formatting to display them as integer values.  Try something like:

xAxis.setStandardTickUnits(new NumberTickUnitSource(true));
