### ISSUE TITLE
XYLineChartTest import jdk.jfr.Unsigned

### ISSUE THREAD

**Issue by trashgod** [jfree/jfreechart#176]
This recent [commit](https://github.com/jfree/jfreechart/commit/974c482aab44e6b02931934beb28155f0fabe62e) modified `XYLineChartTest` to import [`jdk.jfr.Unsigned`](https://docs.oracle.com/javase/10/docs/api/jdk/jfr/Unsigned.html). As this class is new in Java 9, does this represent a new baseline?

**Comment by jfree** [comment]
Oops, not sure at all how that got in there.  It is unused, so I removed it.  Thanks for the report.
