### ISSUE TITLE
NPE in CrosshairOverlay when the label is empty

### ISSUE THREAD

**Issue by ebourg** [jfree/jfreechart#194]
There is a NullPointerException in the `drawHorizontalCrosshair` and `drawVerticalCrosshair` methods of `CrosshairOverlay` when the label is an empty string. This happens because `TextUtils.calculateRotatedStringBounds()` returns a null Shape for empty strings and the calling methods do not test this case.

**Comment by jfree** [comment]
Thanks for the report.   I committed a fix.

**Comment by ebourg** [comment]
Thank you!
