### ISSUE TITLE
1.5.1 PeriodAxis.draw() does not honor axis.isVisible()

### ISSUE THREAD

**Issue by markus-olbrich** [jfree/jfreechart#198]
PeriodAxis.setVisible(false) will not hide the axis, but reduces axis space.

This can be shown in the Demo Example by 
/* --------------------
 * PeriodAxisDemo1.java
 * --------------------
 * (C) Copyright 2004-2011, by Object Refinery Limited.
 *
 */

Adding a block of code from DateAxis.draw() Method would solve this.

{code}

    @Override
    public AxisState draw(Graphics2D g2, double cursor, Rectangle2D plotArea,
            Rectangle2D dataArea, RectangleEdge edge,
            PlotRenderingInfo plotState) {

    	
    	// copied from DateAxis  ...
    	
        // if the axis is not visible, don't draw it...
        if (!isVisible()) {
            AxisState state = new AxisState(cursor);
            // even though the axis is not visible, we need to refresh ticks in
            // case the grid is being drawn...
            List ticks = refreshTicks(g2, state, dataArea, edge);
            state.setTicks(ticks);
            return state;
        }
{code}

![1](https://user-images.githubusercontent.com/75995164/102101037-6d67cd80-3e2a-11eb-817e-29b09262bc3a.png)
![2](https://user-images.githubusercontent.com/75995164/102101045-6f319100-3e2a-11eb-81f0-5875a9421cab.png)

**Comment by jfree** [comment]
Thanks for the report.  It's funny how these bugs can lie hidden for so long.  It is fixed for the upcoming 1.5.2 release.
