### ISSUE TITLE
TextTitle throws a different exception from other related classes

### ISSUE THREAD

**Issue by tohidemyname** [jfree/jfreechart#205]
TextTitle  throws NullPointerException fo rnull  parameters:
` public TextTitle(String text, Font font, Paint paint,
                     RectangleEdge position,
                     HorizontalAlignment horizontalAlignment,
                     VerticalAlignment verticalAlignment,
                     RectangleInsets padding) {

        super(position, horizontalAlignment, verticalAlignment, padding);

        if (text == null) {
            throw new NullPointerException("Null 'text' argument.");
        }
        if (font == null) {
            throw new NullPointerException("Null 'font' argument.");
        }
        if (paint == null) {
            throw new NullPointerException("Null 'paint' argument.");
        }
        this.text = text;
        this.font = font;
        this.paint = paint;
        // the textAlignment and the horizontalAlignment are separate things,
        // but it makes sense for the default textAlignment to match the
        // title's horizontal alignment...
        this.textAlignment = horizontalAlignment;
        this.backgroundPaint = null;
        this.content = null;
        this.toolTipText = null;
        this.urlText = null;

    }`
Other classes throw IllegalArgumentException. For example:

` public TextLine(String text, Font font, Paint paint) {
        if (text == null) {
            throw new IllegalArgumentException("Null 'text' argument.");   
        }
        if (font == null) {
            throw new IllegalArgumentException("Null 'font' argument.");   
        }
        if (paint == null) {
            throw new IllegalArgumentException("Null 'paint' argument.");   
        }
        this.fragments = new java.util.ArrayList<>();
        final TextFragment fragment = new TextFragment(text, font, paint);
        this.fragments.add(fragment);
    }`

Another example:

`public TextFragment(String text, Font font, Paint paint,
            float baselineOffset) {
        if (text == null) {
            throw new IllegalArgumentException("Null 'text' argument.");  
        }
        if (font == null) {
            throw new IllegalArgumentException("Null 'font' argument.");
        }
        if (paint == null) {
            throw new IllegalArgumentException("Null 'paint' argument.");
        }
        this.text = text;
        this.font = font;
        this.paint = paint;
        this.baselineOffset = baselineOffset;
    }`

**Comment by trashgod** [comment]
For reference,

- [`TextTitle`](https://github.com/jfree/jfreechart/blob/e746961d1f5735226d786268eae0eef0213cf0c4/src/main/java/org/jfree/chart/title/TextTitle.java#L207)
- [`TextLine`](https://github.com/jfree/jfreechart/blob/e746961d1f5735226d786268eae0eef0213cf0c4/src/main/java/org/jfree/chart/text/TextLine.java#L80)
- [`TextFragment`](https://github.com/jfree/jfreechart/blob/e746961d1f5735226d786268eae0eef0213cf0c4/src/main/java/org/jfree/chart/text/TextFragment.java#L106)
- [_`IllegalArgumentException` or `NullPointerException` for a null parameter?_](https://stackoverflow.com/q/3881/230513)

As an aside, I see the master branch moving towards `Objects.requireNonNull`, which "throws a customized `NullPointerException`."

**Comment by jfree** [comment]
For a short while, I decided moving to Objects.requireNonNull was a good idea because it's the Java standard approach.  However, I came back to my original thinking that IllegalArgumentException is more correct, so I intend to switch back to that.  The link you posted is excellent, I hadn't seen that before.

**Comment by jfree** [comment]
Fixed on the master branch.
