### ISSUE TITLE
Pieplot.getDataset().getValue(0) returns null with an empty dataset. Should throw an IndexOutOfBoundsException

### ISSUE THREAD

**Issue by pkakria** [jfree/jfreechart#212]
I noticed in testing today that getValue(0) returns a null with an empty dataset. I would expect an IndexOutOfBoundsException to be thrown since null is a valid value in the PieDataset. Is this a bug or intended behavior?
Thanks!

**Comment by jfree** [comment]
It looks like a bug to me, fixing it now.
