### ISSUE TITLE
module-info.java not present on v1.5.3

### ISSUE THREAD

**Issue by francogp** [jfree/jfreechart#219]
I cannot use jlink because the maven lib does not contain module-info.class inside the jar

**Comment by jfree** [comment]
JFreeChart 1.5.3 is a Java 8 library so it is not modular.  Work on a modular version (JFreeChart 2.0) is ongoing.

**Comment by trashgod** [comment]
@francogp: As shown [here](https://github.com/jfree/jfreechart#building-jfreechart), you can build and install the latest modular version; I use the maven included in a recent  Netbeans, as shown [here](https://stackoverflow.com/a/66028757/230513); this [gist](https://gist.github.com/trashgod/a3f7581417db19bf5b6dc52d3647a2f9) is a stand-alone example than uses the installed  artifacts.
