### ISSUE TITLE
Missing release tag

### ISSUE THREAD

**Issue by ebourg** [jfree/jfreechart#22]
Hi,

The Git repository is missing the tags for the previous releases. Could you consider adding them please?

Thank you

**Comment by mkrauskopf** [comment]
Hello. I would welcome this as well. I wanted to build my work on specific older release (branch/tag). Now I can only go "manually" through commits while comparing to Changelog, ... there are neither branches nor tags. Thanks.

**Comment by jfree** [comment]
I tagged the previous two releases and will tag new releases going forward.  If anyone requires a tag for an older release for some reason, please request it specifically.
