### ISSUE TITLE
Creating XYLineAnnotation with NaN Values causes ChartUtils.writeChartAsPNG() to hang

### ISSUE THREAD

**Issue by davewichers** [jfree/jfreechart#223]
I have code that is accidentally passing NaN values to the 1st, 3rd, and 4th double values for the 6 parameter constructor of XYLineAnnotation(). See: https://github.com/jfree/jfreechart/blob/master/src/main/java/org/jfree/chart/annotations/XYLineAnnotation.java#L118

This annotation is then added to a chart, and later on, when I invoke ChartUtils.writeChartAsPNG() with this chart, that method simply hangs. Seems like the XYLineAnnotation() constructors should all verify that all the doubles passed to them are actual numbers. Regardless, the ChartUtils.writeChartAsPNG() method shouldn't simply hang.

**Comment by jfree** [comment]
Thanks for the report.  I added some argument validations to prevent this happening.

**Comment by jfree** [comment]
https://github.com/jfree/jfreechart/commit/5ca5d26bb38bafead25f81e88e0938a5d042c2a4
