### ISSUE TITLE
id attribute to svg group object

### ISSUE THREAD

**Issue by netsrotr** [jfree/jfreechart#228]
Taken from [https://www.jfree.org/forum/viewtopic.php?t=116799](https://www.jfree.org/forum/viewtopic.php?t=116799):
Is it now possible with the current version?
Can someone please provide samples how to add an id in java code to have it added for <rect, <circle ... and for group <g within exported SVG as element IDs?

**Comment by jfree** [comment]
I think this one belongs over here: https://github.com/jfree/jfreesvg/issues

In any case, here is a JUnit test that shows (and checks) how to add an element id to a rect:

    @Test
    public void checkDrawRectangle2DWithElementID() {
        SVGGraphics2D g2 = new SVGGraphics2D(200, 100);
        g2.setStroke(new BasicStroke(2.0f, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 3.0f));
        Rectangle2D rect = new Rectangle2D.Double(10.0, 20.0, 30.0, 40.0);
        g2.setRenderingHint(SVGHints.KEY_ELEMENT_ID, "UNIQUE_ELEMENT_ID_1");
        g2.draw(rect);
        assertNull(g2.getRenderingHint(SVGHints.KEY_ELEMENT_ID)); // should be cleared after call
        assertEquals("<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" 
    xmlns:jfreesvg=\"http://www.jfree.org/jfreesvg/svg\" width=\"200.0\" height=\"100.0\" text-rendering=\"auto\" shape- 
    rendering=\"auto\">\n" +
    "<rect id='UNIQUE_ELEMENT_ID_1' x='10.0' y='20.0' width='30.0' height='40.0' style='stroke- 
    width:2.0;stroke:rgb(0,0,0);stroke-opacity:1.0;stroke-linejoin:bevel;stroke-miterlimit:3.0;fill:none'/></svg>",   
    g2.getSVGElement());
        }
