### ISSUE TITLE
TimeSeriesCollectionTest fails

### ISSUE THREAD

**Issue by bleakley** [jfree/jfreechart#23]
When building jfreechart, TimeSeriesCollectionTest fails with
`java.lang.AssertionError: expected:<1.199142E12> but was:<1.1991744E12>`
caused by `assertEquals(1199142000000.0, r.getLowerBound(), EPSILON);`
in `testFindDomainBounds()`

This test fails on Linux, Windows, and MacOS with Java 1.8.0. Does anyone else experience this issue?

**Comment by robertzhab** [comment]
Hi emreatci:
I'm having the same problem.
my exception message is 
Failed tests:   testFindDomainBounds(org.jfree.data.time.TimeSeriesCollectionTes
t): expected:<1.199142E12> but was:<1.1991168E12>

my jfreechart version is 1.5.0,jdk version is 1.7,32-bit。Windows
could you help me how to solve this issue?
Thanks

**Comment by jfree** [comment]
I think this was the fix for this, if not please re-open the ticket:

https://github.com/jfree/jfreechart/commit/f19cea1ef6daccda17b9999264481c5b517861d8#diff-2ec741bf2cabae0448dc219e9f04bf428f1dfc7bca343dcad3ed71338e1d390f
