### ISSUE TITLE
MeterPlot value visibility

### ISSUE THREAD

**Issue by trashgod** [jfree/jfreechart#230]
This recent [question](https://stackoverflow.com/q/67907402/230513) asks how to hide the displayed value in `MeterPlot`. The workaround shown [here](https://stackoverflow.com/a/67910450/230513) simply sets the font size to zero with an empty units string. The [example](https://stackoverflow.com/a/25416067/230513) cited suggests a possible use case in thumbnail displays, etc. If there's interest, I've submitted pull request #231.

**Comment by jfree** [comment]
Thanks, this is merged for inclusion with release 2.0.

**Comment by jfree** [comment]
I added the new valueVisible flag into the equals test.  And also committed these changes to the v1.5.x branch.
