### ISSUE TITLE
Use g2.fillPolygon method drawing Polygons, Why is the border of each polygon displayed?

### ISSUE THREAD

**Issue by chirstwy** [jfree/jfreechart#234]
Extends FastScatterPlot, redefined the render method. When using graphics2d to fill polygons, borders are displayed. These polygon borders should not exist. Why?
![image](https://user-images.githubusercontent.com/10348994/124596160-87373380-de94-11eb-8bca-c15d38e09b88.png)
How to solve this problem?

**Comment by jfree** [comment]
I've seen this effect a number of times with Java2D rendering and it can be difficult to avoid.  One solution is to both fill a shape and draw its outline.
