### ISSUE TITLE
Just upgrade from 1.0.13 (17-Apr-2009) to 1.5.3. Thank you!

### ISSUE THREAD

**Issue by yccheok** [jfree/jfreechart#237]
I just upgraded from 1.0.13 (17-Apr-2009)! to 1.5.3, to solve the graphics pixelized issue in Windows 10

It seems that jfreechart no longer require jcommon.jar dependency

Looks good and thank you for >10 years great library!

**Before**

<img width="441" alt="before" src="https://user-images.githubusercontent.com/308276/130863386-158e8a35-4cdd-4ab2-b934-b40dd949c155.png">

**After**

<img width="470" alt="after" src="https://user-images.githubusercontent.com/308276/130863411-759db7be-88fa-4fcc-ad53-94b92b769fce.png">

**Comment by jfree** [comment]
Hello, 

Thanks for the positive feedback, it's really appreciated! I'm glad the newest version of JFreeChart is working well for you.

 Best regards, David
