### ISSUE TITLE
website gone?

### ISSUE THREAD

**Issue by pdmct** [jfree/jfreechart#242]
I get a 404 trying to go to http://www.jfree.org/jfreechart

**Comment by tracylynne99** [comment]
https://jfree.org/jfreechart/ is the URL

**Comment by pdmct** [comment]
Ok, thanks.

both the link in the README and the link on the front-page of jfree.org  site both go to  a 404

**Comment by jfree** [comment]
Thanks for the report.  My internet provider replaced the certificates yesterday and the http -> https forwarding seems to have stopped.  I've raised a ticket for them to correct that.  In the meantime I'll adjust the links on the front page.

**Comment by tracylynne99** [comment]
Both URLs work now - closing issue.
