### ISSUE TITLE
DateAxis.previousStandardDate() bug

### ISSUE THREAD

**Issue by jfree** [jfree/jfreechart#25]
Issue reported in the forum:

http://www.jfree.org/forum/viewtopic.php?f=3&t=117654

"I've found a bug in DateAxis.previousStandardDate(Date, DateTickUnit). It returns wrong values in case the date given as parameter is already the standard date and the tick unit has a count > 1."

```
public static void main(String[] args)
   {
      Locale.setDefault(Locale.ENGLISH);

      DateAxis da = new DateAxis();
      DateFormat fDateShortTime = new SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault());
      DateTickUnit tickUnit =
         new DateTickUnit(DateTickUnitType.MINUTE, 30, DateTickUnitType.MINUTE, 5, fDateShortTime);

      Date d = new Date(116,3,21,10,00,00);
      for (int m = 0; m < 60; m++)
      {
         d.setMinutes(m);
         Date dnext = da.previousStandardDate(d, tickUnit);
         System.out.println("Input: "+fDateShortTime.format(d) + "  Output: " + fDateShortTime.format(next));
      }
   }
```

**Comment by khalidkh** [comment]
Dear Respondent,


This questionnaire is part of my PhD thesis in the area of improving design smell detection. The purpose of the study is to measure the concordance level of human experts against the design smell detection tools. 
We analyzed the Jfreechart-1.0.x project and detected the set of God Class (Large Class or The Blob) that you can find in this questionnaire. Completing this questionnaire should take about 15 minutes.

I would appreciate your kind attention and cooperation on sending your questionnaire feedback as soon as possible. Notice that all information related to respondent or contained in this questionnaire will be treated in strict confidence.

If you are not currently involved in the project, please forward this message to developers you think are a better target for this questionnaire

To fill the questionnaire click on:

https://docs.google.com/forms/d/e/1FAIpQLSe0bFsqUctarAT-JiGwN3D9DBHowkF9iVvxKSp0IUDAMCQKfQ/viewform?c=0&w=1


Thank you in advance.
Yours sincerely,
Khalid Alkharabsheh
PhD Student at CITIUS, Santiago de Compostela University (Spain).
https://citius.usc.es/equipo/investigadores-en-formacion/khalid-alkharabsheh
