### ISSUE TITLE
line chart only shows a maximum of 10 lines

### ISSUE THREAD

**Issue by asukhu** [jfree/jfreechart#26]
I am using createLineChart, and passing 13 unique line dataset (of type DefaultCategoryDataset). The chart only renders 10 of the 13 lines.

Sample:
final DefaultCategoryDataset dataset = new DefaultCategoryDataset();
for (int i = 0; i < 13; i++)
  {
            
            for (int x = 0; x < d.getValues().length; x++)
            {
                dataset.addValue(x * i, i+"_", xAxisNames.get(x));               
            }
   }

**Comment by altavir** [comment]
I am using it to plot 100+ lines (XYIntervalSeries, but it should not matter) and it works fine. Note that JFreeChart is not thread safe. Check that you are not using concurrent access to the plot.

**Comment by asukhu** [comment]
Thanks Altavir,
Closing issue, i over look some entries in the code where there was no data was specified so that was why the information was not getting rendered... doh.
