### ISSUE TITLE
import jfreechart to netbeans

### ISSUE THREAD

**Issue by moTorky** [jfree/jfreechart#261]
all the People on youtube import all files from lib dir and i can't find it in jfreechart-1.5.3.zip
any one have hint to how i can import the Library to netbeans

**Comment by trashgod** [comment]
As mentioned in [*Migration from JFreeChart 1.0.x*](https://github.com/jfree/jfreechart#migration-from-jfreechart-10x), you can just include `jfreechart-1.5.3.jar`, along with any other tendencies you may have.
