### ISSUE TITLE
Ringplot.setCenterText failure in JfreeChart1.0.19

### ISSUE THREAD

**Issue by weiwei-lu** [jfree/jfreechart#262]
When creating a ring graph using jfreechart1.0.19, the center font of the ring graph is not displayed when the first data in the set is zero
![image](https://user-images.githubusercontent.com/96172360/146155808-e95357aa-597c-4f6d-80ff-c0793ea5156e.png)
I use DefaultPieDataset setValue add data set,when value in the first set is equal to zero then Ringplot.setCenterText is invalidated
![image](https://user-images.githubusercontent.com/96172360/146157940-5fb9f234-a9e3-400d-8bc4-33cc68604b6e.png)
It looks like this

**Comment by weiwei-lu** [comment]
This is what I want
![image](https://user-images.githubusercontent.com/96172360/146159928-46cf2166-95c4-4539-84d5-af19c21d0397.png)

**Comment by trashgod** [comment]
Tested on v1.5.3, you may be able to adapt the approach shown [here](https://stackoverflow.com/a/56672573/230513).

**Comment by weiwei-lu** [comment]
> 在 v1.5.3 上进行了测试，您可以使用[此处显示的方法](https://stackoverflow.com/a/56672573/230513)进行调整。`DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW`

Cool!  I tried the method you gave me and it solved my problem perfectly
