### ISSUE TITLE
Release version 1.5.3.1 with bug #216 fix

### ISSUE THREAD

**Issue by imtiazShakil** [jfree/jfreechart#264]
jfreechart version 1.5.3 is unusable because of bug #216 . This is fixed but no new version with this bug fix is present in maven central.

Can you release a new version 1.5.3.1 with all the bug fixes (like #216 ) .

Thanks

**Comment by trashgod** [comment]
In the interim, can apply bug fix #216 and build like [this](https://stackoverflow.com/a/69653678/230513)?

**Comment by trashgod** [comment]
I've submitted pull request #265 to fix this on the v1.5.x branch. In the interim, you can clone my [repository](https://github.com/trashgod/jfreechart), checkout v1.5.x and build as suggested above. This produces `jfreechart-1.5.4-SNAPSHOT.jar`, which should resolve your problem.

**Comment by imtiazShakil** [comment]
this is now merged in 1.5.4 . So i'm closing the issue
