### ISSUE TITLE
EqualsVerifier: Unable to make field…accessible.

### ISSUE THREAD

**Issue by trashgod** [jfree/jfreechart#266]
When building `jfreechart` v1.5.x, compilation succeeds with just a few warnings, but testing fails with multiple error messages from `EqualsVerifier` of the form "Unable to make field…accessible: module java.base does not "opens java.text" to unnamed module…" This occurs with Java 8, 11 & 17.

    $ git clone https://github.com/jfree/jfreechart.git temp
    $ pushd temp
    $ git checkout v1.5.x
    $ mvn -P release package

**Comment by tracylynne99** [comment]
Strange. Everything builds and tests ok for me (obviously, hahaha, or I wouldn't have done a pull request).

I'm doing a "Build with dependencies" thru NetBeans 12.6. The [partial] output is:

```
Results:

Tests run: 2341, Failures: 0, Errors: 0, Skipped: 0


--- maven-jar-plugin:3.2.0:jar (default-jar) @ jfreechart ---
Building jar: /Users/tracylynne/temp/target/jfreechart-1.5.4-SNAPSHOT.jar

--- maven-install-plugin:2.5.2:install (default-install) @ jfreechart ---
Installing /Users/tracylynne/temp/target/jfreechart-1.5.4-SNAPSHOT.jar to /Users/tracylynne/.m2/repository/org/jfree/jfreechart/1.5.4-SNAPSHOT/jfreechart-1.5.4-SNAPSHOT.jar
Installing /Users/tracylynne/temp/pom.xml to /Users/tracylynne/.m2/repository/org/jfree/jfreechart/1.5.4-SNAPSHOT/jfreechart-1.5.4-SNAPSHOT.pom
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time:  28.815 s
Finished at: 2021-12-29T19:30:09-06:00
------------------------------------------------------------------------
```

**Comment by trashgod** [comment]
Thanks for looking at this. I'm using NetBeans 12.4, Maven 3.6.3, Java 17.0.1, and I get the same result from the IDE or the command line.

    [ERROR] Tests run: 2341, Failures: 4, Errors: 0, Skipped: 0

Can I impose on you to check your Maven version like [this](https://stackoverflow.com/a/66028757/230513)?

**Comment by tracylynne99** [comment]
Oh ok, I understand the problem now. Yeah the jfreechart 1.5.x branch is for those of us who are still restricted to JDK 8 (or below). @jfree isn't that right? And the master branch is where all the latest and greatest JDK compatibilities will be.

**Comment by jfree** [comment]
This branch needs to compile on JDK8 but it should also be error free on the latest JDK as well.  I'm also seeing these errors in Java 17.  Managed to squash all of them now except one in JFreeChartTest.java.

**Comment by trashgod** [comment]
Excellent. After recent [commits](https://github.com/jfree/jfreechart/commits/v1.5.x), I'm now seeing only a single failed test on branch v1.5.x:

    [ERROR] Tests run: 2341, Failures: 1, Errors: 0, Skipped: 0

Now I can go back and see how you did it!

**Comment by jfree** [comment]
I fixed the last one just now.  Thanks for the report!
