### ISSUE TITLE
Version disparity maven-javadoc-plugin

### ISSUE THREAD

**Issue by trashgod** [jfree/jfreechart#269]
While working on a recurrence of issue #232, I noticed a disparity between the `maven-javadoc-plugin` versions specified in the files [`master:pom.xml`](https://github.com/jfree/jfreechart/blob/master/pom.xml) and [`v1.5.x:pom.xml`](https://github.com/jfree/jfreechart/blob/v1.5.x/pom.xml). Both specify `v3.2.0` in the build phase; but the release profiles differ: the `master` branch specifies `v2.9.1`, while the `v1.5.x` branch uses `v3.2.0`. Is this expected?

**Comment by jfree** [comment]
No good reason for it.  I just tried version 3.3.1 and it seems to work, I'll commit the update.
