### ISSUE TITLE
how to mark the value  what i set on axis?

### ISSUE THREAD

**Issue by Jungle92** [jfree/jfreechart#293]
i want to **mark some value** on the axis .just like this:

<img width="564" alt="a" src="https://user-images.githubusercontent.com/29728121/164195035-d1c7b165-c83e-450a-9de5-d7427e611231.png">

 but i can not find any API to resolve it.

**Comment by trashgod** [comment]
I don't know how to mark the axis itself; in the alternative, you might consider one of the `org.jfree.chart.annotations` or a suitable `org.jfree.chart.plot.Marker`. As suggested [here](https://stackoverflow.com/q/71928304/230513), review the sample gallery, cited [here](https://stackoverflow.com/tags/jfreechart/info), for ideas; report any issues you encounter here. For broader guidance, consider posting in the [discussions area](https://github.com/jfree/jfreechart/discussions).

**Comment by Jungle92** [comment]
> I don't know how to mark the axis itself; in the alternative, you might consider one of the `org.jfree.chart.annotations` or a suitable `org.jfree.chart.plot.Marker`. As suggested [here](https://stackoverflow.com/q/71928304/230513), review the sample gallery, cited [here](https://stackoverflow.com/tags/jfreechart/info), for ideas; report any issues you encounter here. For broader guidance, consider posting in the [discussions area](https://github.com/jfree/jfreechart/discussions).

ok,thank u
