### ISSUE TITLE
LogarithmicAxis

### ISSUE THREAD

**Issue by datahaki** [jfree/jfreechart#301]
I wanted to reproduce the example from Mathematica

https://reference.wolfram.com/language/ref/ListLogPlot.html#1122321828

when using JFreeChart default settings (without manual tweaks) the y-axis number/tick labels get crammed

![ListLogPlotDemo](https://user-images.githubusercontent.com/4012178/177034252-ef2d9902-1c95-4d37-8542-e463ced16c39.png)

the ticks seems to be forced as 1, 10, 100, 1000, 1E4, etc.
instead of perhaps 1, 1000, 1E6, etc.

**Comment by trashgod** [comment]
To get a narrower display, try `setExpTickLabelsFlag(true)` on the `LogarithmicAxis`. To mitigate vertical crowding, you may need to increase the height or look at a custom implementation of `refreshTicksVertical()`, as suggested [here](https://stackoverflow.com/search?q=%5Bjfreechart%5D+refreshTicksVertical).

**Comment by datahaki** [comment]
thanks for the info!

I just expected the same default behavior as when using the standard (linear?) axis, which automatically adjusts tick spacing.

The plot below uses same data than from above but linear axis in jFreeChart:

![ListLogPlotDemo](https://user-images.githubusercontent.com/4012178/177041159-42098afe-8915-465f-a020-04bbf71a1cbe.png)

**Comment by trashgod** [comment]
Yes. Note how the newer `LogAxis`, suggested [here](https://stackoverflow.com/a/35645985/230513), extends `ValueAxis ` and overrides `refreshTicks` to achieve this, while the older `LogarithmicAxis` extends `NumberAxis` with a different approach to tick units.

**Comment by datahaki** [comment]
thank you very much - `LogAxis` did the trick!
