### ISSUE TITLE
Minute class without day in equals comparison method

### ISSUE THREAD

**Issue by patrickdalla** [jfree/jfreechart#318]
The Minute class does not considers the day of the date one the method compareTo. It seems to be an error as all other TimePeriod class implementations consider the day, like Second and Hour.

**Comment by trashgod** [comment]
If I'm reading the [code](https://github.com/jfree/jfreechart/tree/master/src/main/java/org/jfree/data/time) correctly, the concrete implementation of `compareTo()` in `Minute` compares to the enclosing `Hour`, which in turn compares to the enclosing `Day`, and so on to `Date`.

**Comment by patrickdalla** [comment]
sorry the problem is not in compareTo, is in the equals.

I'm using hashmaps and the equals method is used to compare objects.

**Comment by trashgod** [comment]
The implementation of `equals()` seems to follow the same pattern. The related tests run correctly, both individually and as a package:

    mvn test -Dtest=MinuteTest
    mvn test -Dtest="org.jfree.data.time.**"

Do you have a test or example that reproduces the problem?

**Comment by patrickdalla** [comment]
The hour comparison is done in equals method against the hour byte value,
not the hour object as in compareTo.

i will give you a test sample tomorrow.

Em sáb., 8 de out. de 2022 22:17, trashgod ***@***.***>
escreveu:

**Comment by patrickdalla** [comment]
The following test does not pass.

@Test 
public void comparison() {
 Minute m1 = new Minute(30, 6, 10, 8, 2021); 
 Minute m2 = new Minute(30, 6, 11, 8, 2021); 
 assertNotEquals(m1, m2);
}

**Comment by trashgod** [comment]
I can reproduce your result, but I'm not sure about the best way forward. In the interim, you may be able to use a `java.util.Date` or `java.time.Instant` as the `Map` key.

```
Minute m1 = new Minute(30, 6, 10, 8, 2021);
Minute m2 = new Minute(30, 6, 11, 8, 2021);
Date d1 = new Date(m1.getFirstMillisecond());
Date d2 = new Date(m2.getFirstMillisecond());
Instant i1 = Instant.ofEpochMilli(m1.getFirstMillisecond());
Instant i2 = Instant.ofEpochMilli(m2.getFirstMillisecond());
```

**Comment by jfree** [comment]
Thanks for spotting this, I committed your test plus the fix.

**Comment by patrickdalla** [comment]
sorry. the problem is not in the compareTo. is in the equals.

I am using hashmaps and the equals is used to compare objects.

Em qui., 6 de out. de 2022 21:08, trashgod ***@***.***>
escreveu:

**Comment by trashgod** [comment]
@patrickdalla: To verify, I did `git checkout v1.5.x` and ran `mvn test -Dtest=MinuteTest#comparison`, which now incorporates your [test](https://github.com/jfree/jfreechart/commit/f3974d700b6638c6617ba09aeed581e33acbb2f6) and produces the correct result. Are you seeing something different?

**Comment by jfree** [comment]
I believe this is fixed.
