### ISSUE TITLE
Unknown database 'jfree'

### ISSUE THREAD

**Issue by schackbrian2012** [jfree/jfreechart#319]
When I try to navigate to the forum for JFreeChart, I get the following error message. Can you please help?

General Error
SQL ERROR [ mysql4 ]
Unknown database 'jfree' [1049]
An sql error occurred while fetching this page. Please contact an administrator if this problem persists.

https://www.jfree.org/forum/

**Comment by trashgod** [comment]
As archived [here](https://web.archive.org/web/20220622145152/https://www.jfree.org/forum/), use GitHub [Discussions](https://github.com/jfree/jfreechart/discussions) for this purpose.

**Comment by jfree** [comment]
The forum (read-only) is back up again.
