### ISSUE TITLE
Unable to find the jcommon.jar  and jfreechart(VersionDatehere).jar files within 1.5.4

### ISSUE THREAD

**Issue by edscottite** [jfree/jfreechart#356]

**Comment by edscottite** [comment]
I've only recently installed the new version and I'm attempting to find the required JCommon and JFreeChart.jar files, I'm confused.

**Comment by trashgod** [comment]
As noted in [Migration](https://github.com/jfree/jfreechart#migration), `JCommon` has been integrated with `JFreeChart`.

**Comment by trashgod** [comment]
For reference, the required artifacts can be downloaded or built from source as seen [here](https://stackoverflow.com/a/69653678/230513).
