### ISSUE TITLE
Crosshairs don't draw in correct spot on datasets with index > 0

### ISSUE THREAD

**Issue by countfloyd** [jfree/jfreechart#36]
If I have multiple datasets on different axes, crosshairs are always drawn according to the axis at index 0. The setDatasetIndex method in CrosshairState seems to never be called in the XYPlot draw method. If I set it manually in the debugger to the proper dataset index, the crosshair is drawn correctly.

**Comment by jfree** [comment]
Good spot...I can reproduce this by making the crosshairs visible in DualAxisDemo2.java.

**Comment by jfree** [comment]
Pushed a fix for this, might still need some more testing.  The change breaks the API but I'm not so worried about that, it shouldn't affect most users, only those that have implemented their own custom renderers.

**Comment by jfree** [comment]
Issue is resolved in the 1.5.0 release.
