### ISSUE TITLE
org.jfree.chart.labels.ItemLabelPosition class not cloneable

### ISSUE THREAD

**Issue by yoeris** [jfree/jfreechart#392]
In an old code base we are using the clone function on a custom subclass of the JfreeChart.
However since this Implementation is using the ItemLabePosition Class it is causing a java.lang.CloneNotSupportedException.

I've seen in the release notes of Version 1.0.10 (8-Jun-2008) a mention of "PublicCloneable is now implemented by a number of classes", I think the ItemLabelPosition Class was forgotten for this.

**Comment by jfree** [comment]
ItemLabelPosition instances are immutable, so cloning them isn't necessary.
