### ISSUE TITLE
Anomaly while building JFreeChart v1.5.5

### ISSUE THREAD

**Issue by trashgod** [jfree/jfreechart#406]
While building JFreeChart v1.5.5, `git checkout v1.5.5` succeeds, but `mvn compile` produces the latest version, `jfreechart-2.0.0-SNAPSHOT.jar`:
```
[INFO] Building JFreeChart-2.0 2.0.0-SNAPSHOT
[INFO]   from pom.xml
```
It appears that tag `v1.5.5` is on the `master` branch, while earlier version tags are on the `v1.5.x` branch. 
```
temp > git branch --contains tags/v1.5.5
* (HEAD detached at v1.5.5)
  master
temp > git branch --contains tags/v1.5.4
  v1.5.x
temp > git branch --contains tags/v1.5.3
  v1.5.x
```
Building from branch `v1.5.x` produces the expected artifacts. Thank you for any guidance.

**Comment by jfree** [comment]
Thanks for the report. It looks like I messed up the release, so I deleted it and released again.  Hopefully it is OK now.

**Comment by trashgod** [comment]
Thank you! The updated tag appears to have restored the expected behavior, and I see that the CI is happier. For reference, an attempt to `git fetch --tags upstream` on a remote-tracking branch was "rejected," as it "would clobber existing tag." Using the `--force` option succeeded.
```
git fetch --tags --force upstream
git push --tags --force
```
