### ISSUE TITLE
Modularization proposal

### ISSUE THREAD

**Issue by altavir** [jfree/jfreechart#41]
JFreeChart is a great (probably the best) graphing library for java, but the one problem I am keeping to bump into when using it is that it is monolithic. It generates a few problems:
- One can't both use the library for legacy java platforms (Java 6 and 7) and use modern features from Java 8 (including JavaFX). As a consequence, there is no JavaFX support in default maven artifact.
- Optional dependencies like `javax.servlet` do complicate things.
- One need to always include the whole huge 2 mb library as a dependency event when one needs only the basic features.

The solution is to modularize the library moving servlet and javafx dependent parts into separate projects. I've done it using gradle [here](https://github.com/altavir/jfreechart) (it could also be done with maven, but gradle is much more convenient for multi-project builds). I tested the builds and publishing to maven local and it works fine without any additional efforts. Later one can also move some more complex plot types into separate modules depending on `:core`.

**Comment by jfree** [comment]
This is a good suggestion, although I am slightly reluctant to break JFreeChart down into a lot of different jar files, since it gets more difficult for people to know which ones they need (Batik is a good example of that, if you ever used it).  I did already move the SWT support classes out into a separate project, I could do the same for JavaFX...let me think about it some more.  What I have been working on is a 1.0.20 release that doesn't include JavaFX and a 1.5.0 release that does include the JavaFX support.  This would at least let people pull in the version they want depending on whether or not they need the JavaFX support.

I can see some benefits in putting the JavaFX support classes into separate project though, so I will give that some more thought.  I want spend too long thinking though, as I want to get new releases done asap. :-)

**Comment by altavir** [comment]
It can be solved by providing multiple distributions. You have fine-grained jars for ones who want it and one uber-jar for ones, who don't. You do not need to create separate projects for that. It could be easily automatically done by gradle or event maven.
For example see [groovy distribution](https://mvnrepository.com/artifact/org.codehaus.groovy). They have a combined `groovy-all` artifact as well as fine-grained parts.

**Comment by altavir** [comment]
For myself I also want a release asap, since I need that javafx support. :)

**Comment by tomas-pluskal** [comment]
Modularizing the release would prevent some confusion with version numbers (1.5 looks newer than 1.0.20, but actually they are the same). It is quite easy to do with maven as well, we have done it with MSDK (https://github.com/msdk/msdk/blob/master/pom.xml). I am happy to help.

**Comment by jfree** [comment]
The version confusion is a good point.  

Regarding the use of a Maven multi-module project versus just using multiple Maven projects with dependencies...what are the pros and cons? I'm mostly using NetBeans and don't run into any problems using multiple dependent Maven projects...but don't know how the support is in Eclipse or IntelliJ.

**Comment by tomas-pluskal** [comment]
I use Eclipse and multi-module projects work just fine. The maven modules can of course have dependencies on each other (in this case, jfreechart-fx would depend on jfreechart-core and FXGraphics2D). As @altavir suggested, you can also use the same setup to build an uber-jar for those who don't use maven.

**Comment by jfree** [comment]
What about separate projects though?  What's the advantage of the multi-module project?  I'll google it also :-)

**Comment by tomas-pluskal** [comment]
I can't think of any advantage of separate projects. The multi-module setup essentially means you have separate projects with one parent pom.xml (so you can build them all together).

**Comment by jfree** [comment]
But say I had modules for JavaFX, SWT and Swing...no-one would want to build them all together, right?  That's partly why I'm thinking separate Maven projects is better.  There is already one for SWT (https://github.com/jfree/jfreechart-swt) by the way, although it probably needs a new JFreeChart release to be effective.

**Comment by tomas-pluskal** [comment]
Maintaining separate projects takes more effort than a single project with multiple modules, IMHO. With the multi-module setup, each module will produce its own jar, so the output is essentially the same as if you have separate projects.

I would recommend to make a 4-module project, with
- jfreechart-core
- jfreechart-swing
- jfreechart-swt
- jfreechart-fx

For those who use maven, they only need to add one of them as a dependency (e.g., they add jfreechart-swing and jfreechart-core is automatically pulled as a dependency). For those who don't use maven, they will have to download two jars, but that doesn't sound like too much effort.

**Comment by altavir** [comment]
IDEA in fact has a very good multi-module project support.
I also do not see any advantage for separate projects. It is much harder to maintain and produces a lot of confusion. The only thing that could be moved to separate project is JavaScript implementation which is independent of the main project.
The current JFreeChart also has a servlet component which should be moved to separate module because it has additional dependancies.

**Comment by jfree** [comment]
Thanks for all the inputs...looking back, somewhere along the way I must have decided on separate projects.  It works for me anyway. :-)
