### ISSUE TITLE
Error / Usage issue in polynomial regression

### ISSUE THREAD

**Issue by WolfgangFahl** [jfree/jfreechart#42]
the following unit tests compares the org.jfree.data.statistics.Regression.getPolynomialRegression
to the apache commons math3 solution. The results of getPolynomialRegression
are 
-5,333 10,000  0,951
while the correct result would be:

coeff   0:  4,000
coeff   1:  2,000
coeff   2:  1,000

you might want to add testcases like the ones in http://alvinalexander.com/java/jwarehouse/commons-math3-3.6.1/src/test/java/org/apache/commons/math3/fitting/PolynomialCurveFitterTest.java.shtml
or improve the documentation on how to use the function correctly.

```
 @Test
  public void testPolynomicalRegression() {
    final double[] coeff = { 4.0, 2.0, 1 }; // 12.9 - 3.4 x + 2.1 x^2
    final PolynomialFunction f = new PolynomialFunction(coeff);
    final WeightedObservedPoints obs = new WeightedObservedPoints();
    double[][] data=new double[2][9];
    for (int i=0;i<=8;i++) {
      double x=i;
      double y=f.value(x);
      data[0][i]=x;
      data[1][i]=y;
      obs.add(x,y);
    }
    final DefaultXYDataset dataset = new DefaultXYDataset();
    dataset.addSeries(0, data);
    double[] preg = org.jfree.data.statistics.Regression.getPolynomialRegression(dataset, 0, 1);
    assertEquals(3,preg.length);
    System.out.println(String.format("%6.3f %6.3f %6.3f",preg[0],preg[1],preg[2]));
    // http://commons.apache.org/proper/commons-math/apidocs/org/apache/commons/math4/fitting/PolynomialCurveFitter.html
    // http://alvinalexander.com/java/jwarehouse/commons-math3-3.6.1/src/test/java/org/apache/commons/math3/fitting/PolynomialCurveFitterTest.java.shtml
    int degree=2;
    final PolynomialCurveFitter fitter = PolynomialCurveFitter.create(degree);
    final PolynomialFunction fitted = new PolynomialFunction(fitter.fit(obs.toList()));
    final double fcoeff[]=fitted.getCoefficients();
    for (int i=0;i<fcoeff.length;i++) {
      System.out.println(String.format("coeff %3d: %6.3f",i,fcoeff[i]));
    }
```

**Comment by erlenmeyer** [comment]
Just stumbled over that issue, and did not want to leave it uncommented.
The documentation of Regression.getPolynomialRegression states that
- the third parameter is the order of the regression
- the method returns an array of length order+2, where the last value indicates the correlation coefficient

So, in the test above, a linear regression was fitted through the data, giving a regression with slope of 10, offset of -5.333, and R2 of 0.951.  Using an instance of org.apache.commons.math3.fitting.PolynomialCurveFitter with a degree of 1 gives the same results for slope and offset.
Just for completion: calling Regression.getPolynomialRegression with a proper "order" value of 2 returns the expected values of 4 (offset), 2 (linear term), 1 (quadratic term), and 1 (R2).

**Comment by trashgod** [comment]
For reference: Some [`Regression`](https://www.jfree.org/jfreechart/javadoc/org/jfree/data/statistics/Regression.html) method tests appear in [`RegressionTest.java`](https://github.com/jfree/jfreechart/blob/master/src/test/java/org/jfree/data/statistics/RegressionTest.java).

**Comment by trashgod** [comment]
I see no substantive, interim change in the relevant API [history](https://github.com/jfree/jfreechart/blob/master/src/main/java/org/jfree/data/statistics/Regression.java). I did not find the API confusing, but this [discussion](https://math.stackexchange.com/q/3323294) offers some perspective.

**Comment by WolfgangFahl** [comment]
@trashgod  thx for the excellent link which also points to https://en.wikipedia.org/wiki/Degree_of_a_polynomial - it seems its often worthwile to habe a proper glossary ...
