### ISSUE TITLE
mvn javadoc:jar - Does not build

### ISSUE THREAD

**Issue by kalee** [jfree/jfreechart#422]
[error.log](https://github.com/user-attachments/files/17356325/error.log)

Attached error.log from: mvn javadoc:jar > error.log

Trying to build jar, source and javadoc files for project. The package jar, and source jar built without any issue.

**Comment by trashgod** [comment]
I see a similar result on the unreleased `master` branch, 2.0.0-SNAPSHOT, although the output in `target/apidocs` is usable. More commonly, I build from the tip of the `v1.5.x` release branch or one of the release tags, where the warnings are not treated errors.

**Comment by kalee** [comment]
I think I understood that.  I did this which seems to have worked:
 git checkout remotes/origin/v1.5.x
mvn javadoc:jar

This successfully built the javadoc.jar file in target for this version.

Thank you!
