### ISSUE TITLE
Wrong package name for jfree-svg packages 

### ISSUE THREAD

**Issue by Theiaz** [jfree/jfreechart#424]
https://github.com/jfree/jfreechart/blob/cb8ff67d983bdee23f690851277e9d4bf10171d4/src/main/java/org/jfree/chart/ChartPanel.java#L2643

This line of the latest release 1.5.5 is incorrect and should be replaced by `org.jfree.svg.SVGGraphics2D`. It prevents the initialiazation of svg export.

**Comment by Theiaz** [comment]
So i need to downgrade two major versions only to fix this bug? Why just not releasing the latest version, it already seems to be fixed on `master` branch.

**Comment by trashgod** [comment]
I'm not sure it's a bug. I see it as  maintaining backward compatibility to Java8, mentioned [here](https://github.com/jfree/jfreechart/discussions/355) and [here](https://github.com/jfree/jfreechart/issues/203), while allowing modular projects to evolve. For example, I had no problem using [JFreeSVG](https://github.com/jfree/jfreesvg) v5.0.6 with Orson Charts FX v2.1.1. The table [here](https://github.com/jfree/jfree-demos?tab=readme-ov-file#jfree-demos), while dated, may be relevant.
