### ISSUE TITLE
Drop Java 8 requirement

### ISSUE THREAD

**Issue by simon04** [jfree/jfreechart#7]
8a2e412fed0f3f4cc03e19d9b3944c9be504f936 changes the source and target Java version from 6 to 8. Is there a specific need for the (admittedly nice) Java 8 features? Using JFreeChart as library in a larger software project immediately induces Java 8 requirement for the whole system.

I would love to stick with Java 6 or 7 since it removes the pressure to quickly update everything to Java 8.

Related to #3.

**Comment by jfree** [comment]
No, the intention is to stick with Java 6 for the build that doesn't contain the JavaFX support (this will be version 1.0.20 when I get the next release out soon).  I plan also to release a version 1.5.0 that requires Java 8 and includes the JavaFX support (this will also get uploaded to the Central Repository).  However, I'm thinking over your suggestion in the other issue #3.

**Comment by simon04** [comment]
So the `pom.xml` modifications from 8a2e412fed0f3f4cc03e19d9b3944c9be504f936 should be reverted? I'm referring to `project.source.level` and `project.target.level` and dropping the exclusion of `org/jfree/chart/fx/**`.

**Comment by jfree** [comment]
Actually, the pom.xml that is committed is the one that will be used for JFreeChart 1.5.0 (with JavaFX support) and will require Java 8.  To build with JDK 6, copy this POM file over:

https://github.com/jfree/jfreechart/blob/master/maven/pom-1.6.xml

I'll use that one to release JFreeChart 1.0.20 (without JavaFX support).

**Comment by simon04** [comment]
Thanks for the clarification and good news to keep Java 6+7 support :smile:

I find having `/pom.xml` in the project root not corresponding to the "default build" confusing, but this might resolve together with #3. Feel free to close this issue…

**Comment by simon04** [comment]
Clarified due to https://github.com/jfree/jfreechart/commit/e4e04e10a80308f2dd5784956d684376faf5b608.
