### ISSUE TITLE
Please provide jar files of the releases

### ISSUE THREAD

**Issue by jondo** [jfree/jfreechart#72]
I have inherited a project that still uses `jfreechart-0.9.21.jar` (from the Sourceforge downloads), and I want to update it to the current version 1.5.0 without having to create the `jfreechart-1.5.0.jar` by myself. Can you please provide it as download again?

**Comment by altavir** [comment]
You can always get it [on maven](https://mvnrepository.com/artifact/org.jfree/jfreechart/1.5.0).
