### ISSUE TITLE
BoxAndWhiskerRenderer: Please add setOutliersVisible()

### ISSUE THREAD

**Issue by jondo** [jfree/jfreechart#74]
Please add a `BoxAndWhiskerRenderer` method `setOutliersVisible(boolean visible)` such that one can switch off the outlier circles and the far-out indicators.

(There is a [corresponding forum thread](http://www.jfree.org/forum/viewtopic.php?f=3&t=117433).)

**Comment by jondo** [comment]
[This old ExtendedBoxAndWhiskerRenderer patch](https://sourceforge.net/p/jfreechart/patches/168/) might also be relevant - according to [this stackoverflow question](https://stackoverflow.com/q/28365288/1389680), it provides `setOutlierPaint()` and `setFaroutPaint()` that could be used to make the markers invisible.

**Comment by jondo** [comment]
That's nice, thanks! I hope your contribution gets merged.

**Comment by AliKarpuzoglu** [comment]
The feature has been added today :D @jfree you could close this issue now

**Comment by jondo** [comment]
Good! Thanks for the update.
