### ISSUE TITLE
XYBlockRenderer does not honor outline properties

### ISSUE THREAD

**Issue by matinh** [jfree/jfreechart#75]
`XYBlockRenderer` derives from `AbstractXYItemRenderer` and thus inherits various methods for setting outline-paint and -stroke (like `setBaseOutlinePaint()`). However, the renderer does not take these properties into account when drawing the blocks.

This can be quite confusing for users, as setting outline-paint or -stroke is possible but has no effect.

**Comment by jfree** [comment]
I applied a change that adds the same flags as used in XYLineAndShapeRenderer, which I think addresses this bug.
